import type {Metadata} from 'next'
import {Noto_Sans_JP} from 'next/font/google'
import './globals.scss'
import {KumaRegistry} from "@kuma-ui/next-plugin/registry";
import Header from "@/components/header";

const notoSansJP = Noto_Sans_JP({subsets: ['latin']})

// Cloudflare Pages使う場合はruntimeをedge
export const runtime = 'nodejs' // process.env.ENV === "release" ? 'edge' : 'nodejs';

export const metadata: Metadata = {
    title: {
        default: 'LaboMato',
        template: '%s - LaboMato'
    },
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: {
    children: React.ReactNode
}) {
    // const session = await getServerSession(authOptions);
    return (
        <html lang="en">
        <head>
            <link rel={'icon'} href={'image/favicon.ico'}/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
        </head>
        <body className={notoSansJP.className}>
        <Header/>
        <KumaRegistry>
            {children}
        </KumaRegistry>
        </body>
        </html>
    )
}
